[toolchain]
channel = "stable"
targets = [
    "aarch64-apple-darwin",
    "x86_64-unknown-linux-gnu",
    "x86_64-pc-windows-msvc",
    "wasm32-unknown-unknown"
]
components = ["cargo", "clippy", "rust-src", "rustc", "rustfmt"]
profile = "minimal"
